export const ADD_TASK='ADD_TASK'
export const REMOVE_TASK='REMOVE_TASK'
export const UPDATE_TASK='UPDATE_TASK'
export const UPDATE_LIST='UPDATE_LIST'
export const GET_TASKS='GET_TASKS'
export const CLEAR_TASKS='GET_TASKS'